-- AlterTable
ALTER TABLE "School" ADD COLUMN "scheduleStartTime" TEXT NOT NULL DEFAULT '07:00',
ADD COLUMN "morningEndTime" TEXT NOT NULL DEFAULT '12:00',
ADD COLUMN "afternoonStartTime" TEXT NOT NULL DEFAULT '14:00',
ADD COLUMN "scheduleEndTime" TEXT NOT NULL DEFAULT '18:00',
ADD COLUMN "slotDurationMinutes" INTEGER NOT NULL DEFAULT 60;
